CREATE TABLE IF NOT EXISTS users (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT NOT NULL, EMAIL TEXT NOT NULL UNIQUE, LOGIN TEXT NOT NULL UNIQUE, PASSWORD TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS usersSession (ID TEXT NOT NULL UNIQUE, USER_NAME TEXT NOT NULL, USER_EMAIL TEXT NOT NULL UNIQUE, USER_LOGIN TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS usersCities (USER_ID TEXT NOT NULL, CITIES TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS userSources (USER_ID TEXT NOT NULL, SOURCE_ID TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sources (ID TEXT NOT NULL, NAME TEXT NOT NULL UNIQUE);
DELETE FROM sources;
INSERT INTO sources (ID,NAME) VALUES ("1","yandex");
INSERT INTO sources (ID,NAME) VALUES ("2","gismeteo");
INSERT INTO sources (ID,NAME) VALUES ("3","weatherCom");